### ISSUE TITLE
I would be grateful if you can share your Firebase Realtime Database Structure

### ISSUE THREAD

**Issue by vatsalcshah** [kashifulhaque/UdemyClone#1]

**Comment by kashifulhaque** [comment]
I did this project for a friend of mine, so I don't really have access to backend. However, I did a quick Database Diagram which I'm willing to share. I hope it'll clear your doubts :)

![fb-realtime-db](https://user-images.githubusercontent.com/37375667/81270129-e2d71880-9067-11ea-9348-d0b779801e01.png)

**Comment by vatsalcshah** [comment]
Thank you for sharing details.
